# Generated by Django 3.0.3 on 2020-07-07 00:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conduite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StatutMarital', models.CharField(max_length=100)),
                ('AnneePermis', models.IntegerField()),
                ('Suspended', models.BooleanField()),
                ('Education', models.CharField(max_length=40)),
                ('EsProprietaire', models.BooleanField()),
                ('Assured', models.BooleanField()),
                ('Profession', models.CharField(max_length=40)),
                ('AnyAccident', models.BooleanField()),
                ('PvInfraction', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Login', models.CharField(max_length=40, unique=True)),
                ('Password', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fabrication', models.IntegerField()),
                ('Marque', models.CharField(max_length=40)),
                ('StyleCaroosserie', models.CharField(max_length=40)),
                ('StatutPossetion', models.CharField(max_length=40)),
                ('Antivol', models.CharField(max_length=40)),
                ('VTC', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('IdClient', models.IntegerField(auto_created=True, editable=False, primary_key=True, serialize=False)),
                ('Prenom', models.CharField(max_length=40)),
                ('Nom', models.CharField(max_length=40)),
                ('Genre', models.CharField(max_length=1)),
                ('DateNaissance', models.DateField()),
                ('Adress', models.CharField(max_length=200)),
                ('Account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coveree_Contract.UserAccount')),
                ('Conduit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coveree_Contract.Conduite')),
                ('Vehicul', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coveree_Contract.Vehicule')),
            ],
        ),
    ]
